version: "3"

services:
  mydomainpage:
    pull_policy: build
    restart: unless-stopped
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"