version: "3.8"

services:
  mydomainpage:
    pull_policy: build
    restart: unless-stopped
    user: ${UID}:${GID}
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"