version: "3"

services:
  mydomainpage:
    pull_policy: build
    restart: unless-stopped
    build:
      args:
        - '-u root:root'
      dockerfile: Dockerfile
      context: .
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"